### ISSUE TITLE
proposal: separate repository for manifest

### ISSUE THREAD

**Issue by dunn** [CodyReichert/qi#31]
Recently Homebrew separated the code behind the `brew` command from the core set of formulae; this allowed for stable releases of Homebrew itself without making users wait for updates to software packages.

Would it be worth doing the same thing here?  Move the `manifest` tree to a separate repo and have `qi --upgrade` just fetch the latest manifest.

**Comment by CodyReichert** [comment]
I've never had an issue with that problem specifically, but that's probably because Qi isn't as widely used as Homebrew and I've always been able to fiddle with it myself. Overall I think it would be a positive change, and probably more along the lines of "best practice" for a package manager. In the case where there are even a few people using packages from Qi, having the dependencies split would be preventative.

So -- I'm down!

What are your thoughts on the best location for the manifests repo (eg `CodyReichert/manifests`)?

**Comment by CodyReichert** [comment]
@dunn Also -- tackling this and any other changes might be easier if you have push access to both Qi and the manifests repo. Would you be interested? (I don't see why not 😀).

I'd still like to go through a PR process for any changes, but I'd be more than comfortable letting you merge. Your changes have been great, and I don't want you to always be waiting on me!

**Comment by dunn** [comment]
> What are your thoughts on the best location for the manifests repo (eg CodyReichert/manifests)?

That sounds good, unless you want to create a GitHub organization for the repos to live under.

> Also -- tackling this and any other changes might be easier if you have push access to both Qi and the manifests repo. Would you be interested? (I don't see why not 😀).

I'd be honored!  And of course I'll still open PRs and get your 👍 for anything non-trivial.

**Comment by CodyReichert** [comment]
@dunn -- alright, I've got you added as a collaborator to qi (this repo). I think you need to accept an invite, but should be good to go after that.

I looked at setting up an organization, but the name `qi` was already taken (unsurprisingly). I think, for now, I'm just going to create a separate, empty, repo `CodyReichert/qi-manifest`, and give you access to that as well.

I'm not opposed to moving to an org at all, but I'd like to get a decent name :D

**Comment by CodyReichert** [comment]
Alright, I went ahead and created [CodyReichert/qi-manifest](https://github.com/CodyReichert/qi-manifest). It's empty right now, but I'm happy to help coordinate moving the current manifest over.

I invited you as a collaborator to [CodyReichert/qi-manifest](https://github.com/CodyReichert/qi-manifest) as well.

**Comment by dunn** [comment]
Thanks!  We can probably use `git filter-branch` to slurp the manifest into the new repo, but then Qi needs to be updated to fetch from the new source.
