### ISSUE TITLE
Loading qi fails (without much output after the first failure)

### ISSUE THREAD

**Issue by bvnierop** [CodyReichert/qi#33]
Unfortunately, there's not much to add other than the title:

    This is SBCL 1.3.3, an implementation of ANSI Common Lisp.
    More information about SBCL is available at <http://www.sbcl.org/>.

    SBCL is free software, provided as is, with absolutely no warranty.
    It is mostly in the public domain; some portions are provided under
    BSD-style licenses.  See the CREDITS and COPYING files in the
    distribution for more information.
    * (load "~/.qi/init.lisp")
    ;
    ; compilation unit aborted
    ;   caught 2 fatal ERROR conditions

    T

**Comment by CodyReichert** [comment]
Hey @bvnierop - thanks for the report! I might need a bit more info, if possible. I just re-installed Qi on my system locally and don't get the same error, but there are a few things we can try:

1. Can you try adding the `(load "/path/to/qi/init.lisp")` to your `.sbclrc` file?
    Although, I'm able to call `load` after inside the SBCL REPL, it could be a way with the order things are loaded.

2. You may also try using the full pathname, depending on your version of SBCL it might work better:
    ```
    (merge-pathnames "/home/cody/workspace/repos/qi/init.lisp" (user-homedir-pathname))
    ```

---

If those both fail:
 - What OS are you on?
 - Do you have the latest Qi from `master` branch?
 - Can you try upgrading the the latest SBCL?

**Comment by CodyReichert** [comment]
Also, @dunn might have some tips -- she's done some work on initializing Qi recently :)

**Comment by bvnierop** [comment]
Hi @CodyReichert , thanks for the quick reply.

After upgrading to the latest version of SBCL, I did manage to get some (read: a lot) of output. The bad news is that I don't have time to filter through it tonight. Since it's way to much to include in the post, I've put it on my public Dropbox account: https://dl.dropboxusercontent.com/u/15706998/shared/qi-output.txt.

After getting that output once, the next time around, the output is the same as in the OP, until SBCL is reinstalled again.

After putting `(load "~/.qi/init.lisp")` in my `.sbclrc`, the problem appears to almost certainly be in the dependency `fad`: https://dl.dropboxusercontent.com/u/15706998/shared/qi-sbclrc-output.txt. Unless that just cuts the output, of course.

Putting the full path in `.sbclrc` gives the same error.
<hr>

- _What OS are you on?_ I've tested on Ubuntu 14.04 and Windows 10.
- _Do you have the latest Qi from master branch?_ Yes
- _Can you try upgrading the the latest SBCL?_ I've tested the upgrade to the latest SBCL only on Ubuntu.

<hr>

Hope that helps.

**Comment by dunn** [comment]
Maybe I just don't know how to read SBCL's output, but I can't even see where the errors are in the logs; and the `load` function itself returns `T`, which is weird.

**Comment by CodyReichert** [comment]
I had the same thought, @dunn. Looking at the info provided and I don't think the error is caused by any recent change. It must be a system or SBCL issue. Not sure yet, but I'm still looking at it to see if I can find anything.

@bvnierop -- thanks a ton for the log output, that's super helpful.

**Comment by bvnierop** [comment]
I've set up a very simple environment to help me figure out where the error comes from.

I have three files:
*error.lisp*: `(defun hello-world (format t "hello, world")) ; we're missing an argument list`
*load-error.lisp*: `(load "error.lisp")`
*compile-error.lisp*: `(compile-file "error.lisp")`

Loading *error.lisp* directly, obviously puts me in the debugger.
Loading *load-error.lisp* also puts me in the debugger.
Loading *compile-error.lisp* succeeds, returning T, with the relevant output being

    ; in: DEFUN FOO
    ;     (DEFUN FOO (FORMAT T "hello, world"))
    ; --> PROGN SB-IMPL::%DEFUN SB-IMPL::%DEFUN SB-INT:NAMED-LAMBDA
    ; ==>
    ;   #'(SB-INT:NAMED-LAMBDA FOO
    ;         (FORMAT T "hello, world")
    ;       (BLOCK FOO))
    ;
    ; caught ERROR:
    ;   Required argument is not a symbol: "hello, world"
    ;
    ; compilation unit finished
    ;   caught 1 ERROR condition


    ; C:/Users/bart/test/error.fasl written
    ; compilation finished in 0:00:00.011
    T
(this is done on a Windows machine, I don't have access to my Ubuntu box from here -- I'll run the test there, too, later, to compare notes)

I've tried a few other very simple errors in *error.lisp* and they all have the same thing in common: `caught ERROR`. Searching for that, or even just `error` in the 8193 line log leads to no useful results, however.

This does, however, explain why `(load "~/.qi/init,lisp")` returns `T`. While compilation itself isn't quite working out, `(load)` doesn't check for that, and loading the file is successful.

**Comment by bvnierop** [comment]
I may have something new. When loading _init.lisp_ from within my editor and SWANK, I get the following output:

    CL-USER> (defpackage #:qi-setup
      (:use #:cl))
    (in-package #:qi-setup)
     ...
    WARNING: redefining QI-SETUP::QI-DIR in DEFUN
    WARNING: redefining QI-SETUP::FIND-ASDF-FASL in DEFUN
    WARNING: redefining QI-SETUP::ENSURE-ASDF-LOADED in DEFUN
    WARNING: redefining QI-SETUP::PUSH-NEW-TO-REGISTRY in DEFUN
    WARNING: redefining QI-SETUP::LOAD-USER-PACKAGES in DEFUN
    ; 
    ; compilation unit aborted
    ;   caught 2 fatal ERROR conditions
    NIL
    #<CFFI:LOAD-FOREIGN-LIBRARY-ERROR "Unable to load any of the alternatives:~%   ~S" {1001EAEC23}>
    QI-SETUP> 

Hope that helps. Shame it doesn't add _what_ it's trying to find alternatives for.

**Comment by dunn** [comment]
So a CFFI error means it's failing to load a non-Lisp library, right?  Could try `(declaim (optimize (debug 3)))` as per http://web.archive.org/web/20160815232841/http://malisper.me/2015/07/07/debugging-lisp-part-1-recompilation/ and see if you get any more output.

**Comment by bvnierop** [comment]
That didn't solve the problem. However, I went a step further and loaded every dependency by hand.

The problem is in `cl-libyaml`, which requires `libyaml` to be installed.

After installing `libyaml`, `init.lisp` loads just fine, and `(qi:hello)` works.

The dependency on `libyaml` should probably be documented.

**Comment by dunn** [comment]
Oh, definitely!  Glad you figured it out, but sorry it was such a hassle.

I wonder if there are other undeclared dependencies.  CL+SSL relies on OpenSSL; most systems come with it, but that may be worth noting anyway.

**Comment by bvnierop** [comment]
That depends on how cross platform Qi is trying to be. Most Windows systems do not come with OpenSSL.

**Comment by dunn** [comment]
Good point; I'll add OpenSSL too.  @CodyReichert do you know if any other libraries have dependencies?

**Comment by bvnierop** [comment]
I spent some time on my Windows machine, and I can verify that there, too, the issues was `cl-libyaml`'s dependency on `libyaml`. As predicted, `cl+ssl`'s dependency on `OpenSSL` was also a problem.

Both `libyaml` and `OpenSSL` can be had on a Windows machine, though, and after installing them, _init.lisp_ now loads correctly and `(qi:hello)` works.

**Comment by dunn** [comment]
Thanks for checking that! I went ahead and updated the README.

**Comment by CodyReichert** [comment]
Awesome - nice job figuring that out!

@dunn -- that's a good question, let me take a look and see if I can think of any others.

I've mostly assumed Linux, and never tested on Windows. If it works, though, then it would be nice to keep it that way and document what needs to be done!

**Comment by bvnierop** [comment]
@CodyReichert  Thanks!

As for working on Windows. I've got `(qi:hello)` working, but there's a problem with actually using Qi. It likely has something to do with `cl-cffi` not being able to find the libyaml DLL at run time.

It doesn't appear to be a Qi issue, so I won't make an issue here. If I ever bother to solve it, I'll report back.
