### ISSUE TITLE
Error downloading chunga tarball on weitz.de, to be replaced with github release

### ISSUE THREAD

**Issue by vindarel** [CodyReichert/qi#56]
Hello,

I went further in qi:install but now I get this error:

```
---> Downloading tarball from http://weitz.de/files/chunga.tar.gz
The value
  NIL
is not of type
  REAL
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1002B8FFA3}>)

Backtrace:
  0: (GZIP-STREAM::PROCESS-DYNAMIC-HUFFMAN-BLOCK #S(GZIP-STREAM::BIT-READER :STREAM #<SB-SYS:FD-STREAM for "file /tmp/qi/archives/chunga-.tar.gz" {100BF14603}> :LAST-BYTE 16 :BITS 6) #<FLEXI-STREAMS::VECTO..
      Locals:
        BR = #S(GZIP-STREAM::BIT-READER :STREAM #<SB-SYS:FD-STREAM for "file /tmp/qi/archives/chunga-.tar.gz" {100BF14603}> :LAST-BYTE 16 :BITS 6)
        BUFFER = #(0 0 0 0 0 0 ...)
        END = 0
        OP = #<FLEXI-STREAMS::VECTOR-OUTPUT-STREAM {100BF223F3}>
```

The first line says it tries to download http://weitz.de/files/chunga.tar.gz, which does not exist any more. The remaining bit lies in `manifest/manifest.lisp`.

```
#S(QI.MANIFEST::MANIFEST-PACKAGE
    :NAME "chunga"
    :URL "http://weitz.de/files/chunga.tar.gz")
```

I had another problem in trying to update this url (to https://github.com/edicl/chunga/archive/v1.1.7.tar.gz released 2 days ago) (`The function ASDF/FIND-SYSTEM::STAMP<= is undefined.` in trying to re-quickload `qi`) so I'll open an issue for now.

Regards.

**Comment by dunn** [comment]
I'm not seeing how to reproduce this error; when I update the URL it seems to work.

**Comment by vindarel** [comment]
Ok, the "stamp" error was certainly my environment, I broke things at the time.

But if you update the url succesfully, don't we have to update it in the manifest ? (that was my first concern)

**Comment by dunn** [comment]
Yes, I just tried it locally.  I'll open a PR on the manifest as soon as I get a chance, unless someone else beats me.

**Comment by dunn** [comment]
The manifest doesn't have enough people updating it frequently enough to use a versioned tarball, so I'll switch it to the git repo.
